# Generated by Django 3.2.5 on 2022-06-19 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0002_auto_20220619_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dweets',
            new_name='Dweet',
        ),
    ]
